name: 'test-on-pr'
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  # push:
  #   branches: [main]
  pull_request:

jobs:
  test-lindo:
    strategy:
      fail-fast: false
      matrix:
        platform: [macos-latest, ubuntu-latest, windows-latest]

    runs-on: ${{ matrix.platform }}
    steps:
      - name: Build
        uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16.15.1'
      - name: Install app dependencies
        run: yarn
      - name: Check linter
        run: yarn lint
      - name: Build the application
        run: yarn build
